allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  "@scarf/scarf": true
  "@swc/core": true
  bcrypt: true
  esbuild: true
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@nestjs/cli@11.0.24'
